/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lijo' at '2/8/16 3:23 PM' with Gradle 2.14
 *
 * @author lijo, @date 2/8/16 3:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
